version: "3.8"

services:
  app:
    build: .
    working_dir: /var/www/todo
    volumes:
      - .:/var/www/todo
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: php -S 0.0.0.0:8000 -t web

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist
    ports:
      - "3307:3306"
